POST http://localhost:3000/api/employees
Content-Type: application/json

{
  "name": "Wirawadi",
  "team": "TEAM_A"
}


###
GET http://localhost:3000/api/employees

###
GET http://localhost:3000/api/employees/cmua6yb040000zsv7atqfrptv

###
PATCH http://localhost:3000/api/employees/cmua6yb040000zsv7atqfrptv
Content-Type: application/json

{
  "name": "M Gilang",
}

###
DELETE http://localhost:3000/api/employees/cmuveagrp0000ywv7z4sqedme



### Create Attendance
POST http://localhost:3000/api/attendance
Content-Type: application/json

{
  "employeeId": "cmua6yb040000zsv7atqfrptv",
  "date": "2026-10-06T00:00:00.000Z",
  "status": "PRESENT",
  "notes": "Masuk tepat waktu"
}

###
GET http://localhost:3000/api/attendance

###
GET http://localhost:3000/api/attendance?date=2026-10-06T00:00:00.000Z

###
GET http://localhost:3000/api/attendance?employeeId=cmua6yb040000zsv7atqfrptv


###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Papan Telur Biasa",
  "pcsPerBundle": 50
}

###
GET http://localhost:3000/api/products

###
PATCH http://localhost:3000/api/products/cmuwbr63y0001rov779o5mdl0
Content-Type: application/json

{
  "name": "Papan Telur Bekas",
  "pcsPerBundle": 50
}

###
POST http://localhost:3000/api/productions
Content-Type: application/json

{
  "productId": "PRODUCT_ID",
  "date": "2026-10-06",
  "bundleQuantity": 141,
  "pcsQuantity": 7050
}